# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0002_auto_20160812_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='owner',
            field=models.CharField(max_length=100, verbose_name='用户名'),
        ),
    ]
