# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0003_auto_20160812_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activate',
            old_name='owner',
            new_name='username',
        ),
    ]
